

cc_library(
    name = "easykv",
    srcs = glob([
        "utils/*.cpp",
    ]),
    hdrs = glob([
        "cache/*.hpp",
        "cache/*.h",
        "pool/*.hpp",
        "utils/*.h",
    ]),
    visibility = ["//visibility:public"],
)
