load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
# 使用 http_archive 方法
http_archive(
    name = "com_github_grpc_grpc", # 命名拉取的包
    urls = ["https://github.com/grpc/grpc/archive/master.tar.gz"], # 给定路径，一般是 "{github项目网址}/archive/{版本}.tar.gz"
    strip_prefix = "grpc-master", # "{github项目名称}-{版本号}"
)
# 拉取该项目的依赖项
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()